Update patch set 4
Patch Set 4: Code-Review+1

Tested on my MacOS, this change successfully fixed the error below:

[INFO] Running org.onap.policy.drools.serverpooltest.Test1
java.io.IOException: Failed to bind to /127.0.63.250:3904
Caused by: java.net.BindException: Can't assign requested address

Patch-set: 4
Reviewer: Gerrit User 5658 <5658@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1