Update patch set 3
Patch Set 3:

This patch gives me other errors with policy-management module when running maven locally : 

----

[ERROR] Tests run: 11, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 1.008 s <<< FAILURE! - in org.onap.policy.drools.system.PolicyEngineTest
[ERROR] test400ControllerAdd(org.onap.policy.drools.system.PolicyEngineTest)  Time elapsed: 0.704 s  <<< ERROR!
java.lang.IllegalArgumentException: java.lang.RuntimeException: Cannot find KieModule: NO-GROUP-ID:NO-ARTIFACT-ID:NO-VERSION
	at org.onap.policy.drools.system.PolicyEngineTest.test400ControllerAdd(PolicyEngineTest.java:241)
Caused by: java.lang.RuntimeException: Cannot find KieModule: NO-GROUP-ID:NO-ARTIFACT-ID:NO-VERSION
	at org.onap.policy.drools.system.PolicyEngineTest.test400ControllerAdd(PolicyEngineTest.java:241)

[ERROR] test401ControllerVerify(org.onap.policy.drools.system.PolicyEngineTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid foo
	at org.onap.policy.drools.system.PolicyEngineTest.test401ControllerVerify(PolicyEngineTest.java:253)

[ERROR] test500Deactivate(org.onap.policy.drools.system.PolicyEngineTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid foo
	at org.onap.policy.drools.system.PolicyEngineTest.test500Deactivate(PolicyEngineTest.java:270)

[ERROR] test501Activate(org.onap.policy.drools.system.PolicyEngineTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid foo
	at org.onap.policy.drools.system.PolicyEngineTest.test501Activate(PolicyEngineTest.java:283)





[ERROR] Errors:
[ERROR]   DroolsControllerFactoryTest.buildNullController:37 » Runtime Cannot find KieMo...
[ERROR]   DroolsControllerFactoryTest.getNullController:47 » IllegalState DroolControlle...
[ERROR]   PolicyControllerFactoryTest.testPatchStringDroolsConfiguration:164 » IllegalArgument
[ERROR]   PolicyEngineTest.test400ControllerAdd:241 » IllegalArgument java.lang.RuntimeE...
[ERROR]   PolicyEngineTest.test401ControllerVerify:253 » IllegalArgument Invalid foo
[ERROR]   PolicyEngineTest.test500Deactivate:270 » IllegalArgument Invalid foo
[ERROR]   PolicyEngineTest.test501Activate:283 » IllegalArgument Invalid foo
[ERROR]   AggregatedPolicyControllerTest.testFactory:146 » IllegalArgument java.lang.Run...

---

Patch-set: 3
Reviewer: Gerrit User 5658 <5658@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0