Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Can you check if this tool breaks, Francesco?  https://git.onap.org/policy/drools-pdp/tree/policy-management/src/main/server-gen/bin/telemetry (as it goes by the swagger spec).

Hi Jorge, it does break. Since the /swagger.json endpoint it's nulled. What do you suggest?

/opt/app/policy/bin $ sh policy --debug start
  L []: Policy Management (pid 270) is running'
  L []: Policy Management (pid 270) is running
/opt/app/policy/bin $ sh telemetry 
  sh: true: unknown operand
  generating new spec ..
  error: cannot generate telemetry spec

Patch-set: 2