Update patch set 2
Patch Set 2: Code-Review-2

This still does not work - please refer to Bruno's review that fixed the issue by not hard coding any IP address (no we are not going to require developers to change their etc/hosts):

[INFO] Running org.onap.policy.drools.serverpooltest.Test1
java.io.IOException: Failed to bind to /127.0.63.250:3904

Patch-set: 2
Label: Code-Review=-2